server {
    listen       6610;
    listen  [::]:6610;
    server_name  localhost;
    location / {
        proxy_pass http://xx.xxx.xx.xx:6610;
        proxy_intercept_errors on;
        error_page 301 302 307 = @handle_redirects;
    }
    location @handle_redirects {
        set $saved_redirect_location '$upstream_http_location';
        proxy_pass $saved_redirect_location;
    }
}